linters:
  ColorVariable:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  UrlFormat:
    enabled: false
